export const SUBSCRIPTION_DI_TOKENS = {
  SUBSCRIPTION_REPOSITORY: Symbol('SUBSCRIPTION_REPOSITORY'),
  SUBSCRIPTION_SERVICE: Symbol('SUBSCRIPTION_SERVICE'),
  SUBSCRIPTION_NOTIFIER: Symbol('SUBSCRIPTION_NOTIFIER'),
  SUBSCRIPTION_TOKEN_SERVICE: Symbol('SUBSCRIPTION_TOKEN_SERVICE'),
  SUBSCRIPTION_EMAIL_SENDER: Symbol('SUBSCRIPTION_EMAIL_SENDER'),

  WEATHER_CLIENT: Symbol('WEATHER_CLIENT'),
};
