services:

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - apps/subscription/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: weather-redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  weather-service:
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    container_name: weather-service
    env_file:
      - apps/weather/.env
    depends_on:
      - redis
      - pushgateway
    networks:
      - app-network
    ports:
      - "3003:3003"

  email-service:
    build:
      context: .
      dockerfile: apps/email/Dockerfile
    container_name: email-service
    env_file:
      - apps/email/.env
    networks:
      - app-network
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  subscription-service:
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile
    container_name: subscription-service
    env_file:
      - apps/subscription/.env
    depends_on:
      - postgres
      - weather-service
      - email-service
      - rabbitmq
    networks:
      - app-network
    ports:
      - "3002:3002"

  notification-service:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
    container_name: notification-service
    env_file:
      - apps/notification/.env
    depends_on:
      - subscription-service
      - email-service
      - weather-service
      - rabbitmq
    networks:
      - app-network
    ports:
      - "3005:3005"

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    env_file:
      - apps/gateway/.env
    depends_on:
      - subscription-service
      - weather-service
      - email-service
      - notification-service
    networks:
      - app-network
    ports:
      - "3006:3006"

  pushgateway:
    image: prom/pushgateway
    ports:
      - '9091:9091'
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  prom-tail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

volumes:
  pgdata:
  grafana-storage:

networks:
  app-network:
    driver: bridge