services:

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - apps/subscription/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: weather-redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  weather-service:
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    container_name: weather-service
    env_file:
      - apps/weather/.env
    depends_on:
      - redis
    networks:
      - app-network
    ports:
      - "3003:3003"

  email-service:
    build:
      context: .
      dockerfile: apps/email/Dockerfile
    container_name: email-service
    env_file:
      - apps/email/.env
    networks:
      - app-network
    ports:
      - "3001:3001"

  subscription-service:
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile
    container_name: subscription-service
    env_file:
      - apps/subscription/.env
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "3002:3002"

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge