services:
  test-db:
    image: postgres:15
    container_name: test-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"