export const WEATHER_DI_TOKENS = {
  WEATHER_SERVICE: Symbol('WEATHER_SERVICE'),
  WEATHER_MAPPER: Symbol('WEATHER_MAPPER'),
  WEATHER_API_CLIENT: Symbol('WEATHER_API_CLIENT'),
  VISUAL_CROSSING_CLIENT: Symbol('VISUAL_CROSSING_CLIENT'),
  VISUAL_CROSSING_MAPPER: Symbol('VISUAL_CROSSING_MAPPER'),
};
