export const WEATHER_DI_TOKENS = {
  BASE_WEATHER_SERVICE: Symbol('BASE_WEATHER_SERVICE'),
  WEATHER_SERVICE: Symbol('WEATHER_SERVICE'),
  WEATHER_MAPPER: Symbol('WEATHER_MAPPER'),
  WEATHER_API_CLIENT: Symbol('WEATHER_API_CLIENT'),
  VISUAL_CROSSING_CLIENT: Symbol('VISUAL_CROSSING_CLIENT'),
  VISUAL_CROSSING_MAPPER: Symbol('VISUAL_CROSSING_MAPPER'),
  WEATHER_HANDLER: Symbol('WEATHER_HANDLER'),
};
