export const DI_TOKENS = {
  WEATHER_API_CLIENT: Symbol('WEATHER_API_CLIENT'),
  SUBSCRIPTION_REPOSITORY: Symbol('SUBSCRIPTION_REPOSITORY'),
  EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
  WEATHER_SERVICE: Symbol('WEATHER_SERVICE'),
  SUBSCRIPTION_SERVICE: Symbol('SUBSCRIPTION_SERVICE'),
  SUBSCRIPTION_NOTIFIER: Symbol('SUBSCRIPTION_NOTIFIER'),
  SUBSCRIPTION_TOKEN_SERVICE: Symbol('SUBSCRIPTION_TOKEN_SERVICE'),
  LOGGER_SERVICE: Symbol('LOGGER_SERVICE'),
  EMAIL_JOB_SERVICE: Symbol('EMAIL_JOB_SERVICE'),
  WEATHER_MAPPER: Symbol('WEATHER_MAPPER'),
};
