export const NOTIFICATION_DI_TOKENS = {
  EMAIL_JOB_SERVICE: Symbol('EMAIL_JOB_SERVICE'),
  WEATHER_CLIENT: Symbol('WEATHER_CLIENT'),
  SUBSCRIPTION_CLIENT: Symbol('SUBSCRIPTION_CLIENT'),
  EMAIL_CLIENT: Symbol('EMAIL_CLIENT'),
  NOTIFICATION_EMAIL_SENDER: Symbol('NOTIFICATION_EMAIL_SENDER'),
};
