name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node & dependencies
        uses: ./.github/actions/install

      - name: Run ESLint
        run: npm run lint:check
