name: Run Tests
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node & dependencies
        uses: ./.github/actions/install

      - name: Run unit tests
        run: npm run test:unit
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node & dependencies
        uses: ./.github/actions/install

      - name: Start PostgreSQL Database
        run: |
          docker compose -f docker-compose.test.yml up -d && sleep 5s

      - name: Run integration tests
        run: npm run test:integration