name: Run Tests
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node & dependencies
        uses: ./.github/actions/install

      - name: Start PostgreSQL Database
        run: |
          docker compose -f docker-compose.test.yml up -d && sleep 5s

      - name: Start migration
        run: npm run test:migrate
      - name: Run tests
        run: npm run test