name: Unit Tests
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node & dependencies
        uses: ./.github/actions/install

      - name: Run unit tests
        run: npm run test:unit